# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:android)
platform :android do

    desc "this lane distributes QA app to testers"
    lane :distributeQA do
        gradle(
  task: "clean assemble",
  build_type: "Debug"
)
 firebase_app_distribution(
            service_credentials_file: "firebase-distribution-key.json",
            app: ENV['APP_ID_TEST'],
            release_notes: "Lots of amazing new features to test out!",
            groups: "qa"
        )
       
    end
  
end